pipeline{
   agent any
   tools{
    maven 'M2_HOME'
   }

   stages{
    stage("SonarQube Analysis"){
        steps{
            withSonarQubeEnv('sonarqube'){
                sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=skrajewski1_geo-app'
            }
        }
    }
    stage("Maven"){
        steps{
            sh 'mvn clean validate compile install test package'
        }
    }
    stage('Upload Artifact'){
        steps{
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
            target/bio*.jar \
            "http://52.90.14.183:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
        }
    }
    stage('Docker Login'){
        steps{
            sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 637423414297.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
    
    stage('docker Image Build'){
        steps{
            sh 'docker build -t utc-app-dev:v.${BUILD_ID} .'
            sh 'docker build -t utc-app-dev:latest .'
        }
    }

    stage('Image Tagging'){
        steps{
            sh 'docker tag utc-app-dev:v.${BUILD_ID} 637423414297.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
            sh 'docker tag utc-app-dev:v.${BUILD_ID} 637423414297.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
        }
    }

    stage('Docker Push'){
        steps{
            sh 'docker push 637423414297.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:latest'
            sh 'docker push 637423414297.dkr.ecr.us-east-1.amazonaws.com/utc-app-dev:v.${BUILD_ID}'
        }
    }
}
}